repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
  - id: sqlfluff
    name: sqlfluff
    entry: sqlfluff lint --disable-progress-bar
    language: system
    require_serial: true
    types_or: [sql]
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.13
  hooks:
    - id: uv-export
