name: Cron
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2,6'
jobs:
  create-source-data:
    uses: ./.github/workflows/create-source-data.yaml
    secrets: inherit
  run-processing:
    uses: ./.github/workflows/run-processing.yaml
    secrets: inherit
    needs: create-source-data
  report-success:
    runs-on: ubuntu-latest
    needs: run-processing
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.HEALTHCHECK_PING_URL }}
